### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by BHydden** [happybai/ghost-go#57]
Not sure if it is just me or not but both the tsumego and kifu pages are blank.

Windows 10
Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)
EDIT: updated to Version 64.0.3282.119 (Official Build) (64-bit) - problem persists

**Comment by happybai** [comment]
Thank you! ssl certificate expired. It should be working now.

**Comment by BHydden** [comment]
Yes this is now resolved thank you for the quick fix <3
